DRAFT = 'draft'
CREATED = 'created'
PUBLISHED = 'published'
HIDDEN = 'hidden'
FINISHED = 'finished'
ACTIVE = 'active'
INACTIVE = 'inactive'
INVITED = 'invited'
REMOVED = 'removed'
SUSPENDED = 'suspended'
VERIFIED = 'verified'
BANNED = 'banned'
ACCEPTED = 'accepted'
REJECTED = 'rejected'


PLAN_STATES = (
  (DRAFT, DRAFT),
  (CREATED, CREATED),
  (PUBLISHED, PUBLISHED),
  (HIDDEN, HIDDEN),
  (FINISHED, FINISHED)
)

PLAN_ORGANIZATION_STATES = (
  (CREATED, CREATED),
  (ACTIVE, ACTIVE),
  (INACTIVE, INACTIVE)
)

MEMBERSHIP_STATES = (
  (CREATED, CREATED),
  (INVITED, INVITED),
  (ACTIVE, ACTIVE),
  (INACTIVE, INACTIVE),
  (REMOVED, REMOVED),
  (SUSPENDED, SUSPENDED)
)

USER_STATES = (
  (CREATED, CREATED),
  (VERIFIED, VERIFIED),
  (BANNED, BANNED)
)

JOIN_REQUEST_STATES = (
  (CREATED, CREATED),
  (ACCEPTED, ACCEPTED),
  (REJECTED, REJECTED)
)
  