# Generated by Django 4.1.4 on 2023-02-11 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('draft', 'draft'), ('created', 'created'), ('published', 'published'), ('hidden', 'hidden'), ('finished', 'finished')], default='draft', max_length=50, protected=True, verbose_name='Plan state')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50)),
                ('company_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='PlanOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('created', 'created'), ('active', 'active'), ('inactive', 'inactive')], default='created', max_length=50, protected=True, verbose_name='PlanOrganization state')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PlanOrganization',
                'verbose_name_plural': 'PlanOrganizations',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='role',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_team',
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='invitation_code',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(related_name='memberships', to='accounting.role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'created'), ('invited', 'invited'), ('active', 'active'), ('inactive', 'inactive'), ('removed', 'removed'), ('suspended', 'suspended')], default='created', max_length=50, protected=True, verbose_name='Membership state'),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='qwe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'created'), ('verified', 'verified'), ('banned', 'banned')], default='created', max_length=50, protected=True, verbose_name='User state'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='document_type',
            field=models.CharField(choices=[('DH', 'de_honorarios'), ('DCV', 'de_compraventa'), ('DPDS', 'de_prestacion_de_servicios'), ('CDPE', 'comprobante_de_pago_electronico'), ('LDCP', 'libros_de_contabilidad_principal'), ('LC', 'libro_caja'), ('LD', 'libro_diario'), ('LM', 'libro_mayor'), ('LDH', 'libro_de_honorarios'), ('LDIYB', 'libro_de_inventarios_y_balances'), ('LDC', 'libros_de_control'), ('LF', 'libro_fut'), ('LA', 'libros_auxiliares'), ('LDCOMP', 'libro_de_compras'), ('LDREM', 'libro_de_remuneraciones'), ('LDRET', 'libro_de_retenciones'), ('NDC', 'notas_de_credito'), ('NDB', 'notas_de_debito'), ('LETDCAM', 'letras_de_cambio'), ('P', 'pagares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'compra'), ('V', 'venta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('DH', 'de_honorarios'), ('DCV', 'de_compraventa'), ('DPDS', 'de_prestacion_de_servicios'), ('CDPE', 'comprobante_de_pago_electronico'), ('LDCP', 'libros_de_contabilidad_principal'), ('LC', 'libro_caja'), ('LD', 'libro_diario'), ('LM', 'libro_mayor'), ('LDH', 'libro_de_honorarios'), ('LDIYB', 'libro_de_inventarios_y_balances'), ('LDC', 'libros_de_control'), ('LF', 'libro_fut'), ('LA', 'libros_auxiliares'), ('LDCOMP', 'libro_de_compras'), ('LDREM', 'libro_de_remuneraciones'), ('LDRET', 'libro_de_retenciones'), ('NDC', 'notas_de_credito'), ('NDB', 'notas_de_debito'), ('LETDCAM', 'letras_de_cambio'), ('P', 'pagares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'compra'), ('V', 'venta')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='planorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.organization'),
        ),
        migrations.AddField(
            model_name='planorganization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.plan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plans',
            field=models.ManyToManyField(through='accounting.PlanOrganization', to='accounting.plan'),
        ),
    ]
