# Generated by Django 4.1.4 on 2023-03-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='accounting.role'),
        ),
    ]
