# Generated by Django 4.1.4 on 2023-02-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_company_invitation_membership_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='accounting.company')),
            ],
            options={
                'verbose_name': 'Accounting',
                'verbose_name_plural': 'Accountings',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_recoverable_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_of_non_recoverable_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_recoverable_iva_code', models.CharField(max_length=2)),
                ('net_fixed_asset', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_asset_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_common_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_without_right_to_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_not_withheld', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cigars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tobacco_cigarettes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elaborated_cigars', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('current_partnership', models.BooleanField(default=False)),
                ('legal_representative', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.company')),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('document_type', models.CharField(choices=[('', 'de_honorarios'), ('', 'de_compraventa'), ('', 'de_prestacion_de_servicios'), ('', 'comprobante_de_pago_electronico'), ('', 'libros_de_contabilidad_principal'), ('', 'libro_caja'), ('', 'libro_diario'), ('', 'libro_mayor'), ('', 'libro_de_honorarios'), ('', 'libro_de_inventarios_y_balances'), ('', 'libros_de_control'), ('', 'libro_fut'), ('', 'libros_auxiliares'), ('', 'libro_de_compras'), ('', 'libro_de_remuneraciones'), ('', 'libro_de_retenciones'), ('', 'notas_de_credito'), ('', 'notas_de_debito'), ('', 'letras_de_cambio'), ('', 'pagares')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('', 'compra'), ('', 'venta')], max_length=20)),
                ('rut_customer_or_supplier', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('folio', models.CharField(max_length=20)),
                ('document_date', models.DateField()),
                ('acknowledgement_date', models.DateField()),
                ('exempt_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('code_other_tax', models.CharField(max_length=20)),
                ('value_other_tax', models.DecimalField(decimal_places=3, max_digits=10)),
                ('other_tax', models.CharField(max_length=20)),
                ('nce_or_nde_on_purchase_invoice', models.CharField(max_length=20)),
                ('claim_date', models.DateField()),
                ('total_iva_withheld', models.DecimalField(decimal_places=2, max_digits=20)),
                ('partial_iva_withheld', models.DecimalField(decimal_places=2, max_digits=20)),
                ('own_iva', models.DecimalField(decimal_places=2, max_digits=20)),
                ('third_party_iva', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rut_liquid_commission_invoice', models.CharField(max_length=20)),
                ('net_liquid_commission_invoice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission_exempt_liquid_invoice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('iva_out_of_time', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_of_document_reference', models.CharField(max_length=20)),
                ('folio_reference_document', models.CharField(max_length=20)),
                ('foreign_recipients_identity_number', models.CharField(max_length=20)),
                ('nationality_foreign_recipients', models.CharField(max_length=20)),
                ('construction_company_loan', models.DecimalField(decimal_places=2, max_digits=20)),
                ('free_zone_tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('packaging_warranty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('no_cost_sales_indicator', models.CharField(max_length=20)),
                ('periodic_service_indicator', models.CharField(max_length=20)),
                ('non_billable_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_period', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ticket_sales_national_transportation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sale_of_international_transportation_tickets', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounting')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('category', models.CharField(max_length=20)),
                ('taxable', models.BooleanField()),
                ('start_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.company')),
            ],
            options={
                'verbose_name': 'Economic Activity',
                'verbose_name_plural': 'Economic Activities',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('cellphone_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.company')),
            ],
            options={
                'verbose_name': 'Company Contact',
                'verbose_name_plural': 'Company Contacts',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.company')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
    ]
