# Generated by Django 4.1.4 on 2023-03-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_membership_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='roles',
        ),
    ]
