# Generated by Django 4.1.4 on 2023-03-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_membership_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
