# Generated by Django 4.1.4 on 2023-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_company_address_alter_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_refered',
            field=models.CharField(max_length=50, verbose_name='tax refered'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='kind',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_organization',
            field=models.IntegerField(default='d'),
            preserve_default=False,
        ),
    ]
