# Generated by Django 4.1.4 on 2023-03-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounting.membership'),
        ),
    ]
